## 参考文献：
pickle使用: http://www.cnblogs.com/pzxbc/archive/2012/03/18/2404715.html

sklearn: http://www.cnblogs.com/jasonfreak/p/5448462.html

数据和特征决定了机器学习的上限，而模型和算法只是逼近这个上限而已。

---
## 特征工程学习用例


使用sklearn中的IRIS（鸢尾花）数据集来对特征处理功能进行说明。IRIS数据集由Fisher在1936年整理，包含4个特征（Sepal.Length（花萼长度）、Sepal.Width（花萼宽度）、Petal.Length（花瓣长度）、Petal.Width（花瓣宽度）），特征值都为正浮点数，单位为厘米。目标值为鸢尾花的分类（Iris Setosa（山鸢尾）、Iris Versicolour（杂色鸢尾），Iris Virginica（维吉尼亚鸢尾））。导入IRIS数据集的代码如下：

In [16]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
iris = load_iris()


In [17]:
iris.data[0:10]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

L0范数是指向量中非0的元素的个数。

L1范数是指向量中各个元素绝对值之和

L2范数是指向量各元素的平方和然后求平方根

### 1. 预处理学习

In [19]:
#标准化，返回值为标准化后的数据
from sklearn.preprocessing import StandardScaler
StandardScaler().fit_transform(iris.data);

In [25]:
#区间缩放，返回值为缩放到[0, 1]区间的数据
from sklearn.preprocessing import MinMaxScaler
MinMaxScaler().fit_transform(iris.data)

array([[ 0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 0.11111111,  0.5       ,  0.05084746,  0.04166667],
       [ 0.08333333,  0.45833333,  0.08474576,  0.04166667],
       [ 0.19444444,  0.66666667,  0.06779661,  0.04166667],
       [ 0.30555556,  0.79166667,  0.11864407,  0.125     ],
       [ 0.08333333,  0.58333333,  0.06779661,  0.08333333],
       [ 0.19444444,  0.58333333,  0.08474576,  0.04166667],
       [ 0.02777778,  0.375     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.45833333,  0.08474576,  0.        ],
       [ 0.30555556,  0.70833333,  0.08474576,  0.04166667],
       [ 0.13888889,  0.58333333,  0.10169492,  0.04166667],
       [ 0.13888889,  0.41666667,  0.06779661,  0.        ],
       [ 0.        ,  0.41666667,  0.01694915,  0.        ],
       [ 0.41666667,  0.83333333,  0.03389831,  0.04166667],
       [ 0.38888889,  1.        ,  0.08474576,  0.125     ],
       [ 0.30555556,  0.

标准化与归一化的区别

　　简单来说，标准化是依照特征矩阵的列处理数据，其通过求z-score的方法，将样本的特征值转换到同一量纲下。归一化是依照特征矩阵的行处理数据，其目的在于样本向量在点乘运算或其他核函数计算相似性时，拥有统一的标准，也就是说都转化为“单位向量”。规则为l2的归一化公式如下

In [26]:
#归一化，返回值为归一化后的数据
from sklearn.preprocessing import Normalizer
Normalizer().fit_transform(iris.data);

### 2. 数据变换

In [27]:
from sklearn.preprocessing import PolynomialFeatures
#多项式转换
PolynomialFeatures().fit_transform(iris.data)

array([[  1.  ,   5.1 ,   3.5 , ...,   1.96,   0.28,   0.04],
       [  1.  ,   4.9 ,   3.  , ...,   1.96,   0.28,   0.04],
       [  1.  ,   4.7 ,   3.2 , ...,   1.69,   0.26,   0.04],
       ..., 
       [  1.  ,   6.5 ,   3.  , ...,  27.04,  10.4 ,   4.  ],
       [  1.  ,   6.2 ,   3.4 , ...,  29.16,  12.42,   5.29],
       [  1.  ,   5.9 ,   3.  , ...,  26.01,   9.18,   3.24]])

### 3. 特征选择

特征是否发散：如果一个特征不发散，例如方差接近于0，也就是说样本在这个特征上基本上没有差异，这个特征对于样本的区分并没有什么用。

特征与目标的相关性：这点比较显见，与目标相关性高的特征，应当优选选择。

**根据特征选择的形式又可以将特征选择方法分为3种：**

Filter：过滤法，按照发散性或者相关性对各个特征进行评分，设定阈值或者待选择阈值的个数，选择特征。

Wrapper：包装法，根据目标函数（通常是预测效果评分），每次选择若干特征，或者排除若干特征。

Embedded：嵌入法，先使用某些机器学习的算法和模型进行训练，得到各个特征的权值系数，根据系数从大到小选择特征。类似于Filter方法，但是是通过训练来确定特征的优劣。

*使用sklearn中的feature_selection库来进行特征选择*

---
# 作业相关

个人理解：
1. 由于数据没给特征矩阵，所以要先自己根据数据构造特征矩阵
2. 没有缺失值，维数不大，所以基本不需要降维，规格化也不用，因为特征值都是我们生成的，但预处理需要处理noise之类

### 1.特征构造（参考别人的构造先构造一波）
1.1. Count of vowels in word

1.2. The vowels in word

1.3. The phonemes before each vowel 

1.4. The phonemes after each vowel 

1.5. prefix in word

1.6. suffix in word（验证无用，方差为0）

In [28]:
import helper
import pandas as pd
import numpy as np
import sklearn

import matplotlib.pyplot as plt

training_data = helper.read_data('./asset/training_data.txt')
testing_data = helper.read_data('./asset/tiny_test.txt')
#定义元辅音集合
vowel = "AA, AE, AH, AO, AW, AY, EH, ER, EY, IH, IY, OW, OY, UH, UW".replace(",","").split()
consonant = "P, B, CH, D, DH, F, G, HH, JH, K, L, M, N, NG, R, S, SH, T, TH, V, W, Y, Z, ZH".replace(",","").split()

#元、辅音合集合
vowelAndconsonan = vowel + consonant;

In [29]:
print(testing_data)

['DATA:D EY T AH', 'MINING:M AY N IH NG', 'MACHINE:M AH SH IY N', 'LEARNING:L ER N IH NG']


In [30]:
df_train = pd.read_csv('./asset/pd_TrainData.txt', sep=':')
df_train.head()


Word                Pronunciation
0          COED                  K OW1 EH2 D
1       PURVIEW                P ER1 V Y UW2
2         HEHIR              HH EH1 HH IH0 R
3      MUSCLING         M AH1 S AH0 L IH0 NG
4  NONPOISONOUS  N AA0 N P OY1 Z AH0 N AH0 S

In [31]:
#获取前缀后缀, 直接用了别人的
def s_has_pre(s):
    pre = "an,dis,in,ig,il,im,ir,ne,n,non,neg,un,male,mal,pseudo,mis,de\
    un,anti,ant,contra,contre,contro,counter,ob,oc,of,op,with,by,circum,\
    circu,de,en,ex,ec,es,fore,in,il,im,ir,inter,intel,intro,medi,med,mid,out,\
    over,post,pre,pro,sub,suc,suf,sug,sup,sur,sus,sur,trans,under,up,\
    ante,anti,ex,fore,mid,medi,post,pre,pri,out,over,post,pre,pro,sub,suc,suf,\
    sug,sum,sup,sur,sus,super,sur,trans,under,up,ante,anti,ex,fore,mid,medi,post,\
    pre,pri,pro,re,by,extra,hyper,out,over,sub,suc,sur,super,sur,under,vice,com,\
    cop,con,cor,co,syn,syl,sym,al,over,pan,ex,for,re,se,dia,per,pel,trans，ad,\
    ac,af,ag,an,ap,ar,as,at,ambi,bin,di,twi,tri,thir,deca,deco,dec,deci,hecto,\
    hect,centi,kilo,myria,mega,micro,multi,poly,hemi,demi,semi,pene,arch,auto,bene,\
    eu,male,mal,macro,magni,micro,aud,bio,ge,phon,tele,\
    ac,ad,af,ag,al,an,ap,as,at,an,ab,abs,acer,acid,acri,act,ag,acu,aer,aero,ag,agi,\
    ig,act,agri,agro,alb,albo,ali,allo,alter,alt,am,ami,amor,ambi,ambul,ana,ano,andr,\
    andro,ang,anim,ann,annu,enni,ante,anthrop,anti,ant,anti,antico,apo,ap,aph,aqu,arch,\
    aster,astr,auc,aug,aut,aud,audi,aur,aus,aug,auc,aut,auto,bar,be,belli,bene,bi,bine,\
    bibl,bibli,biblio,bio,bi,brev,cad,cap,cas,ceiv,cept,capt,cid,cip,cad,cas,calor,capit,\
    capt,carn,cat,cata,cath,caus,caut,cause,cuse,cus,ceas,ced,cede,ceed,cess,cent,centr,\
    centri,chrom,chron,cide,cis,cise,circum,cit,civ,clam,claim,clin,clud,clusclaus,co,cog,\
    col,coll,con,com,cor,cogn,gnos,com,con,contr,contra,counter,cord,cor,cardi,corp,cort,\
    cosm,cour,cur,curr,curs,crat,cracy,cre,cresc,cret,crease,crea,cred,cresc,cret,crease,\
    cru,crit,cur,curs,cura,cycl,cyclo,de,dec,deca,dec,dign,dei,div,dem,demo,dent,dont,derm,\
    di,dy,dia,dic,dict,dit,dis,dif,dit,doc,doct,domin,don,dorm,dox,duc,duct,dura,dynam,dys,\
    ec,eco,ecto,en,em,end,epi,equi,erg,ev,et,ex,exter,extra,extro,fa,fess,fac,fact,fec,fect,\
    fic,fas,fea,fall,fals,femto,fer,fic,feign,fain,fit,feat,fid,fid,fide,feder,fig,fila,fili,\
    fin,fix,flex,flect,flict,flu,fluc,fluv,flux,for,fore,forc,fort,form,fract,frag,frai,fuge,\
    fuse,gam,gastr,gastro,gen,gen,geo,germ,gest,giga,gin,gloss,glot,glu,glo,gor,grad,gress\
    ,gree,graph,gram,graf,grat,grav,greg,hale,heal,helio,hema,hemo,her,here,hes,hetero,hex\
    ,ses,sex,homo,hum,human,hydr,hydra,hydro,hyper,hypn,an,ics,ignis,in,im,in,im,il,ir,infra\
    ,inter,intra,intro,ty,jac,ject,join,junct,judice,jug,junct,just,juven,labor,lau,lav,lot\
    ,lut,lect,leg,lig,leg,levi,lex,leag,leg,liber,liver,lide,liter,loc,loco,log,logo,ology\
    ,loqu,locut,luc,lum,lun,lus,lust,lude,macr,macer,magn,main,mal,man,manu,mand,mania,mar\
    ,mari,mer,matri,medi,mega,mem,ment,meso,meta,meter,metr,micro,migra,mill,kilo,milli,min\
    ,mis,mit,miss,mob,mov,mot,mon,mono,mor,mort,morph,multi,nano,nasc,nat,gnant,nai,nat,nasc\
    ,neo,neur,nom,nom,nym,nomen,nomin,non,non,nov,nox,noc,numer,numisma,ob,oc,of,op,oct,oligo\
    ,omni,onym,oper,ortho,over,pac,pair,pare,paleo,pan,para,pat,pass,path,pater,patr,path,pathy\
    ,ped,pod,pedo,pel,puls,pend,pens,pond,per,peri,phage,phan,phas,phen,fan,phant,fant,phe,phil\
    ,phlegma,phobia,phobos,phon,phot,photo,pico,pict,plac,plais,pli,ply,plore,plu,plur,plus,pneuma\
    ,pneumon,pod,poli,poly,pon,pos,pound,pop,port,portion,post,pot,pre,pur,prehendere,prin,prim,\
    prime,pro,proto,psych,punct,pute,quat,quad,quint,penta,quip,quir,quis,quest,quer,re,reg,recti\
    ,retro,ri,ridi,risi,rog,roga,rupt,sacr,sanc,secr,salv,salu,sanct,sat,satis,sci,scio,scientia,\
    scope,scrib,script,se,sect,sec,sed,sess,sid,semi,sen,scen,sent,sens,sept,sequ,secu,sue,serv,\
    sign,signi,simil,simul,sist,sta,stit,soci,sol,solus,solv,solu,solut,somn,soph,spec,spect,spi,\
    spic,sper,sphere,spir,stand,stant,stab,stat,stan,sti,sta,st,stead,strain,strict,string,stige,\
    stru,struct,stroy,stry,sub,suc,suf,sup,sur,sus,sume,sump,super,supra,syn,sym,tact,tang,tag,tig,\
    ting,tain,ten,tent,tin,tect,teg,tele,tem,tempo,ten,tin,tain,tend,tent,tens,tera,term,terr,terra,\
    test,the,theo,therm,thesis,thet,tire,tom,tor,tors,tort,tox,tract,tra,trai,treat,trans,tri,trib,\
    tribute,turbo,typ,ultima,umber,umbraticum,un,uni,vac,vade,vale,vali,valu,veh,vect,ven,vent,ver,\
    veri,verb,verv,vert,vers,vi,vic,vicis,vict,vinc,vid,vis,viv,vita,vivi,voc,voke,vol,volcan,volv\
    ,volt,vol,vor,with,zo".replace(" ","").split(",")
    for i in pre:
        if s.startswith(i.upper()):
            return 1
    return 0

# 验证无用
def s_has_end(s):
    end = "ee,ese,esque,se,eer,ique,ty,less,ness,ly,ible,able,ion,ic,ical,al,ian,ic,\
    ion,ity,ment,ed,es,er,est,or,ary,ory,ous,cy,ry,ty,al,ure,ute,ble,ar,ly,less,ful,ing,\
    ,inal,tion,sion,osis,oon,sce,\
    que,ette,eer,ee,aire,able,ible,acy,cy,ade,age,al,al,ial,ical,an,ance,ence,ancy,\
    ency,ant,ent,ant,ent,ient,ar,ary,ard,art,ate,ate,ate,ation,cade,drome,ed,ed,en,en,\
    ence,ency,er,ier,er,or,er,or,ery,es,ese,ies,es,ies,ess,est,iest,fold,ful,ful,fy,ia,\
    ian,iatry,ic,ic,ice,ify,ile,ing,ion,ish,ism,ist,ite,ity,ive,ive,ative,itive,ize,less,\
    ly,ment,ness,or,ory,ous,eous,ose,ious,ship,ster,ure,ward,wise,ize,phy,ogy,ity,ion,ic,ical,al".replace(" ","").split(",")
    for i in end:
        if s.endswith(i.upper()):
            return 1
    return 0

In [32]:
#输入训练单词和音标获取：目标值，元音数, 音标序列，元音序列, 有无对应前缀，有无对应后缀
def getInfoOfPronsFromTrain(word, prons):
    hasPre = s_has_pre(word)
    hasEnd = s_has_end(word)
    pronsSeq = []
    vowelsSeq = []
    stressVowelIndex = 0
    count = 0
    sub_prons = prons.split(' ')
    for i in range(len(sub_prons)):
        if sub_prons[i][-1].isdigit():
            vowelsSeq.append(vowel.index(sub_prons[i][0:-1])) #取得元音在元音集合中的序号
            pronsSeq.append(vowelAndconsonan.index(sub_prons[i][0:-1])) #取得元音在元、辅音集合中的序号
            count+=1
            if sub_prons[i][-1] == '1':
                stressVowelIndex = count
        else:
            pronsSeq.append(vowelAndconsonan.index(sub_prons[i])) #取得辅音在元辅、音集合中的序号
    return stressVowelIndex, count, pronsSeq, vowelsSeq, hasPre, hasEnd

#输入测试单词和目标获取：元音数, 音标序列，元音序列, 有无对应前缀，有无对应后缀
def getInfoOfPronsFromTest(word, prons):
    hasPre = s_has_pre(word)
    hasEnd = s_has_end(word)
    pronsSeq = []
    vowelsSeq = []
    count = 0
    sub_prons = prons.split(' ')
    for i in range(len(sub_prons)):
        if sub_prons[i] in voewl:
            vowelsSeq.append(vowel.index(sub_prons[i])) #取得元音在元音集合中的序号
            count+=1
        pronsSeq.append(vowelAndconsonan.index(sub_prons[i])) #取得辅音在元辅、音集合中的序号
    return stressVowelIndex, count, pronsSeq, vowelsSeq, hasPre, hasEnd

In [33]:
## test
a1, a2 = training_data[3].split(':')
print(a1, a2)
b1, b2, b3, b4, b5, b6 = getInfoOfPronsFromTrain(a1, a2)
print(b1, b2, b3, b4, b5, b6)

MUSCLING M AH1 S AH0 L IH0 NG
1 3 [26, 2, 30, 2, 25, 9, 28] [2, 2, 9] 0 1


In [34]:
targetArr = []
countArr = []
pronsSeqArr = [] 
vowelsSeqArr = []
hasPreArr = []
hasEndArr = []

for i in range(len(training_data)):
    t_word, t_prons = training_data[i].split(':')
    t1, t2, t3, t4, t5, t6 = getInfoOfPronsFromTrain(t_word, t_prons)
    targetArr.append(t1)
    countArr.append(t2)
    pronsSeqArr.append(t3) 
    vowelsSeqArr.append(t4)
    hasPreArr.append(t5)
    hasEndArr.append(t6)

In [35]:
df = pd.DataFrame({'data' : training_data,
                   'target' : targetArr,
                   'count' : countArr,
                   'pronsSeq' : pronsSeqArr,
                   'vowelsSeq' : vowelsSeqArr,
                   'hasPre' : hasPreArr,
                   'hasEnd' : hasEndArr
})


df.head()


count                                      data  hasEnd  hasPre  \
0      2                          COED:K OW1 EH2 D       1       1   
1      2                     PURVIEW:P ER1 V Y UW2       1       1   
2      2                     HEHIR:HH EH1 HH IH0 R       1       0   
3      3             MUSCLING:M AH1 S AH0 L IH0 NG       1       0   
4      4  NONPOISONOUS:N AA0 N P OY1 Z AH0 N AH0 S       1       1   

                                pronsSeq  target      vowelsSeq  
0                        [24, 11, 6, 18]       1        [11, 6]  
1                    [15, 7, 34, 36, 14]       1        [7, 14]  
2                     [22, 6, 22, 9, 29]       1         [6, 9]  
3              [26, 2, 30, 2, 25, 9, 28]       1      [2, 2, 9]  
4  [27, 0, 27, 15, 12, 37, 2, 27, 2, 30]       2  [0, 12, 2, 2]

In [36]:
pronsSeqArr

[[24, 11, 6, 18],
 [15, 7, 34, 36, 14],
 [22, 6, 22, 9, 29],
 [26, 2, 30, 2, 25, 9, 28],
 [27, 0, 27, 15, 12, 37, 2, 27, 2, 30],
 [25, 0, 34, 6, 24, 10, 2],
 [16, 2, 24, 2, 25, 18],
 [10, 32, 2, 27],
 [30, 5, 26, 6, 18],
 [37, 0, 26, 16, 14],
 [16, 9, 24, 30, 2, 25],
 [26, 2, 21, 35, 5, 29],
 [8, 18, 2, 27],
 [18, 7, 5, 2, 30],
 [25, 11, 18, 7, 37],
 [21, 1, 27, 9, 24],
 [6, 27, 30, 9, 27, 23, 7],
 [21, 29, 5, 18, 7],
 [4, 32, 16, 3, 29, 18],
 [16, 14, 30, 24, 2],
 [26, 0, 27, 18, 0, 32, 11],
 [27, 5, 23, 9, 29, 10, 2, 27],
 [24, 0, 28, 21, 6, 25, 11, 30, 10],
 [25, 1, 31, 2, 26],
 [16, 11, 32, 11, 37],
 [26, 7, 24, 9, 27],
 [6, 16, 7, 32],
 [22, 6, 21, 27, 7],
 [0, 34, 0, 25, 11, 37],
 [29, 8, 27, 10],
 [20, 9, 21, 36, 7, 37],
 [22, 9, 17, 22, 5, 24, 30],
 [31, 0, 29, 16, 7],
 [24, 1, 26, 16, 11, 18, 10, 2, 27],
 [29, 1, 30, 24, 2, 27],
 [6, 18, 25, 9, 27],
 [22, 1, 26, 25, 2, 32, 30],
 [33, 3, 29, 2, 15],
 [32, 6, 29, 2, 20, 5, 9, 28],
 [15, 1, 15, 30, 2, 27],
 [29, 6, 24, 32, 2, 20,

In [37]:
df.describe()

count   hasEnd        hasPre        target
count  50000.000000  50000.0  50000.000000  50000.000000
mean       2.567340      1.0      0.443140      1.364080
std        0.696358      0.0      0.496761      0.595326
min        2.000000      1.0      0.000000      1.000000
25%        2.000000      1.0      0.000000      1.000000
50%        2.000000      1.0      0.000000      1.000000
75%        3.000000      1.0      1.000000      2.000000
max        4.000000      1.0      1.000000      4.000000

研究发现hasEnd的方差为0，舍去

In [38]:
df.groupby(['count', 'target']).count()

data  hasEnd  hasPre  pronsSeq  vowelsSeq
count target                                            
2     1       24435   24435   24435     24435      24435
      2        3184    3184    3184      3184       3184
3     1        8938    8938    8938      8938       8938
      2        6903    6903    6903      6903       6903
      3         554     554     554       554        554
4     1        1441    1441    1441      1441       1441
      2        2135    2135    2135      2135       2135
      3        2356    2356    2356      2356       2356
      4          54      54      54        54         54

In [39]:
#构造特征矩阵0
labels_0 = []
for i in range(len(training_data)):
    labels_0.append([countArr[i]])

In [40]:
#构造特征矩阵1
labels_1 = []
for i in range(len(training_data)):
    labels_1.append([countArr[i], hasPreArr[i]])

In [41]:
labels_1

[[2, 1],
 [2, 1],
 [2, 0],
 [3, 0],
 [4, 1],
 [4, 1],
 [2, 0],
 [2, 0],
 [2, 1],
 [2, 0],
 [2, 1],
 [2, 0],
 [2, 1],
 [3, 0],
 [2, 0],
 [2, 0],
 [3, 1],
 [2, 0],
 [2, 1],
 [2, 0],
 [3, 1],
 [4, 1],
 [4, 0],
 [2, 0],
 [2, 0],
 [2, 1],
 [2, 0],
 [2, 0],
 [3, 0],
 [2, 0],
 [2, 1],
 [2, 0],
 [2, 0],
 [4, 0],
 [2, 0],
 [2, 0],
 [2, 0],
 [2, 0],
 [4, 1],
 [2, 0],
 [3, 1],
 [3, 1],
 [2, 1],
 [2, 0],
 [3, 1],
 [2, 0],
 [2, 0],
 [4, 1],
 [2, 1],
 [3, 0],
 [3, 0],
 [4, 1],
 [2, 0],
 [2, 0],
 [2, 0],
 [3, 0],
 [2, 1],
 [2, 1],
 [2, 0],
 [2, 1],
 [2, 0],
 [2, 0],
 [2, 1],
 [3, 1],
 [2, 0],
 [2, 1],
 [3, 0],
 [2, 0],
 [2, 0],
 [3, 1],
 [2, 0],
 [3, 0],
 [3, 1],
 [2, 0],
 [2, 0],
 [4, 0],
 [2, 0],
 [2, 0],
 [4, 1],
 [4, 0],
 [2, 0],
 [2, 0],
 [2, 1],
 [2, 1],
 [3, 0],
 [2, 0],
 [4, 0],
 [3, 0],
 [2, 1],
 [2, 0],
 [2, 0],
 [3, 1],
 [3, 1],
 [2, 0],
 [2, 0],
 [2, 1],
 [2, 1],
 [3, 1],
 [2, 1],
 [2, 1],
 [4, 1],
 [2, 0],
 [2, 1],
 [2, 0],
 [2, 1],
 [2, 1],
 [4, 1],
 [2, 0],
 [2, 0],
 [2, 1],
 [2, 0],
 

In [42]:
from sklearn import tree
from sklearn.cross_validation import train_test_split 
from sklearn.metrics import f1_score 

x_train, x_test, y_train, y_test = train_test_split(labels_1, targetArr, test_size = 0.3) 

### 决策树

In [43]:

#使用信息熵作为划分标准，对决策树进行训练
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf.fit(x_train, y_train)

#系数反映每个特征的影响力。越大表示该特征在分类中起到的作用越大
clf.feature_importances_

array([ 0.92689046,  0.07310954])

In [44]:
answer = clf.predict(x_train)
answer2 = clf.predict(x_test)
print(answer)
# print(np.mean( answer == y_train))
print('f1 for train = ' , f1_score(y_train, answer, average='micro'))
print('f1 for test = ' , f1_score(y_test, answer2, average='micro'))


[3 1 1 ..., 1 1 1]
f1 for train =  0.718457142857
f1 for test =  0.7146


### 贝叶斯

In [45]:
from sklearn import linear_model
clf_bayes = linear_model.BayesianRidge()
clf_bayes.fit(x_train, y_train)
answer = clf_bayes.predict(x_train).round() #取整
answer2 = clf_bayes.predict(x_test).round()
print('f1 for train = ' , f1_score(y_train, answer, average='micro'))
print('f1 for test = ' , f1_score(y_test, answer2, average='micro'))

f1 for train =  0.669342857143
f1 for test =  0.669733333333
